# Generated by Django 5.2.13 on 2026-04-22 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appku', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kontak', models.CharField(blank=True, default='', max_length=100)),
                ('alamat', models.TextField(blank=True, default='')),
                ('telepon', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kontak', models.CharField(blank=True, default='', max_length=100)),
                ('alamat', models.TextField(blank=True, default='')),
                ('telepon', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='produk',
            name='deskripsi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='produk',
            name='stok',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produk',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produks', to='appku.kategori'),
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_harga', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('processing', 'Diproses'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesanans', to='appku.pelanggan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesanans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('harga_saat_itu', models.IntegerField(default=0)),
                ('subtotal', models.IntegerField(default=0)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pesanans', to='appku.produk')),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='appku.pesanan')),
            ],
        ),
        migrations.AddField(
            model_name='produk',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produks', to='appku.supplier'),
        ),
    ]
