                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Generated by Django 5.2.13 on 2026-04-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appku', '0002_kategori_pelanggan_supplier_produk_deskripsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='nama',
            field=models.CharField(default='', max_length=200),
        ),
    ]
